name: CMAKE BUILD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      trigger_name:
        description: 'Trigger Name'
        required: true
        default: 'CMake Build'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: CMake Build
      run: |
        cmake -GNinja -Bbuild
        ninja -Cbuild
