name: Print Done Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      trigger_name:
        description: 'Trigger Name'
        required: true
        default: 'Print Done'

jobs:
  print_done:
    runs-on: ubuntu-latest

    steps:
    - name: Print Done
      run: echo "PROBABLY_WORKS"
